OpsiExplore:
  groups:
    - SchedulerU00
    - OpsiExplore
    - { task: OpsiGeneral, group: OpsiGeneral }
  displays:
    - [ SchedulerU00, OpsiExplore ]

#  default:
#    Scheduler:
#      Enable: true
#  override:
#    OpsiExplore:
#      SpecialRadar: false
#  trigger:
#    on:
#      - OpsiExplore.OpsiExplore.SpecialRadar == true
#    set:
#  trigger_show: OpsiExplore.OpsiExplore.SpecialRadar == true

OpsiDaily:
  groups:
    - SchedulerU00
    - OpsiDaily
    - task: OpsiGeneral
      group: OpsiGeneral
  displays: flat

OpsiGeneral:
  groups:
    - OpsiGeneral

OpsiAshAssist:
  groups:
    - SchedulerU00
    - OpsiAshAssist
  displays: flat
