OpsiExplore:
  groups:
    Scheduler: SchedulerU00
    OpsiExplore:
    OpsiGeneral:
      task: OpsiGeneral
  displays:
    - [ Scheduler, OpsiExplore ]

#  default:
#    Scheduler:
#      Enable: true
#  override:
#    OpsiExplore:
#      SpecialRadar: false
#  trigger:
#    on:
#      - OpsiExplore.OpsiExplore.SpecialRadar == true
#    set:
#  trigger_show: OpsiExplore.OpsiExplore.SpecialRadar == true

OpsiDaily:
  groups:
    Scheduler: SchedulerU00
    OpsiDaily:
    OpsiGeneral:
      task: OpsiGeneral
  displays: flat

OpsiGeneral:
  groups:
    OpsiGeneral:

OpsiAshAssist:
  groups:
    Scheduler: SchedulerU00
    OpsiAshAssist:
  displays: flat
