"""
Tests for the tmp file machinery of alasio.ext.path.atomic.

Covered: random_id(), is_tmp_file(), to_tmp_file(), to_nontmp_file(),
windows_attempt_delay() and replace_tmp().

The tests run on the in-memory fake filesystem (the fs fixture), the
real disk is never touched. The Windows retry loops are tested on every
platform by patching IS_WINDOWS, the retries never wait in real time
(record_sleeps) and the file locks are simulated by breaking the os
functions (break_function).
"""
import os
import re

import pytest

from alasio.ext.path import atomic
from alasio.ext.path.atomic import (
    WINDOWS_MAX_ATTEMPT, file_read_text, file_write, is_tmp_file, random_id, replace_tmp, to_nontmp_file, to_tmp_file,
    windows_attempt_delay
)
from alasio.testing.filesystem import fs  # noqa: F401
from tests.ext.path.atomic.helpers import break_function, record_sleeps


class TestRandomId:
    """Test cases for random_id()."""

    def test_format(self):
        """Every id should be 6 alphanumeric characters."""
        ids = [random_id() for _ in range(100)]
        assert all(re.fullmatch(r'[A-Za-z0-9]{6}', rid) for rid in ids)

    def test_random(self):
        """The ids should not repeat."""
        ids = [random_id() for _ in range(100)]
        assert len(set(ids)) > 1


class TestIsTmpFile:
    """Test cases for is_tmp_file()."""

    @pytest.mark.parametrize('file, expected', [
        # regular tmp names
        ('file.txt.ABC123.tmp', True),
        ('file.txt.abc123.tmp', True),
        ('data.ABC123.tmp', True),
        ('x.ABC123.tmp', True),
        ('a.tmp.ABC123.tmp', True),
        # full paths, PathStr.is_tmp_file passes the path
        ('/data/file.txt.ABC123.tmp', True),
        # missing the separator dot before the random id
        ('dataABC123.tmp', False),
        ('data_ABC123.tmp', False),
        # not a tmp suffix
        ('file.txt.ABC123.tmp.bak', False),
        ('file.txt.ABC123.TMP', False),
        # too short for a tmp name
        ('ABC123.tmp', False),
        ('ABCDEF.tmp', False),
        ('x.tmp', False),
        ('', False),
        # the random id part is not alphanumeric
        ('file.txt.tmp', False),
        ('file.txt.abc12_.tmp', False),
        ('file.txt.abc12-.tmp', False),
    ])
    def test_is_tmp_file(self, file, expected):
        """Only the names generated by to_tmp_file() should be tmp files."""
        assert is_tmp_file(file) is expected


class TestToTmpFile:
    """Test cases for to_tmp_file()."""

    @pytest.mark.parametrize('file', ['file.txt', '/data/file.bin', 'C:/data/a', 'data', 'a.tmp'])
    def test_to_tmp_and_back(self, file):
        """The generated name should be a tmp file that converts back."""
        tmp = to_tmp_file(file)
        assert tmp.startswith(f'{file}.')
        assert tmp.endswith('.tmp')
        assert is_tmp_file(tmp) is True
        assert to_nontmp_file(tmp) == file

    def test_to_tmp_unique(self):
        """Every call should generate its own suffix."""
        names = {to_tmp_file('/data/file.txt') for _ in range(20)}
        assert len(names) == 20


class TestToNontmpFile:
    """Test cases for to_nontmp_file()."""

    @pytest.mark.parametrize('file, expected', [
        ('file.txt.ABC123.tmp', 'file.txt'),
        ('/data/file.bin.a1B2c3.tmp', '/data/file.bin'),
        ('file.txt', 'file.txt'),
        ('x.tmp', 'x.tmp'),
        ('file.txt.ABC123.TMP', 'file.txt.ABC123.TMP'),
    ])
    def test_to_nontmp_file(self, file, expected):
        """The tmp suffix should be stripped, other names kept as-is."""
        assert to_nontmp_file(file) == expected


class TestWindowsAttemptDelay:
    """Test cases for windows_attempt_delay()."""

    def test_attempt_delays(self):
        """The delay of every attempt should double per attempt, capped at 1s."""
        delays = [windows_attempt_delay(attempt) for attempt in range(17)]
        assert delays == [
            # 0.05 * 2 ** attempt
            0.05, 0.1, 0.2, 0.4, 0.8,
            # capped at 1s
            1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
        ]

    def test_clamped_attempts(self):
        """Attempts outside the meaningful range should use the bound of the range."""
        assert windows_attempt_delay(-1) == 0.05
        assert windows_attempt_delay(-100) == 0.05
        assert windows_attempt_delay(11) == 1.0
        assert windows_attempt_delay(100) == 1.0


class TestReplaceTmp:
    """Test cases for replace_tmp()."""

    def test_replace(self, fs):
        """The tmp file should be moved to the target."""
        tmp = to_tmp_file('/data/a.txt')
        file_write(tmp, 'data')
        replace_tmp(tmp, '/data/a.txt')
        assert file_read_text('/data/a.txt') == 'data'
        assert not os.path.exists(tmp)

    def test_replace_over_existing(self, fs):
        """An existing target should be replaced."""
        tmp = to_tmp_file('/data/a.txt')
        file_write(tmp, 'new')
        file_write('/data/a.txt', 'old')
        replace_tmp(tmp, '/data/a.txt')
        assert file_read_text('/data/a.txt') == 'new'

    def test_replace_posix(self, fs, monkeypatch):
        """On the other platforms the tmp file is moved right away."""
        monkeypatch.setattr(atomic, 'IS_WINDOWS', False)
        tmp = to_tmp_file('/data/a.txt')
        file_write(tmp, 'data')
        replace_tmp(tmp, '/data/a.txt')
        assert file_read_text('/data/a.txt') == 'data'
        assert not os.path.exists(tmp)

    @pytest.mark.parametrize('is_windows', [True, False])
    def test_replace_missing_tmp(self, fs, monkeypatch, is_windows):
        """A missing tmp file should raise FileNotFoundError, without a retry."""
        monkeypatch.setattr(atomic, 'IS_WINDOWS', is_windows)
        sleeps = record_sleeps(monkeypatch)
        file_write('/data/a.txt', 'old')
        calls = break_function(monkeypatch, os, 'replace', [])
        with pytest.raises(FileNotFoundError):
            replace_tmp('/data/missing.ABC123.tmp', '/data/a.txt')
        assert len(calls) == 1
        assert sleeps.sleeps == []
        assert file_read_text('/data/a.txt') == 'old'

    def test_replace_retries_on_windows(self, fs, monkeypatch):
        """PermissionError should be retried on Windows until it works."""
        monkeypatch.setattr(atomic, 'IS_WINDOWS', True)
        sleeps = record_sleeps(monkeypatch)
        error = PermissionError(13, 'Permission denied')
        tmp = to_tmp_file('/data/a.txt')
        file_write(tmp, 'data')
        calls = break_function(monkeypatch, os, 'replace', [error, error])
        replace_tmp(tmp, '/data/a.txt')
        assert file_read_text('/data/a.txt') == 'data'
        assert len(calls) == 3
        assert sleeps.sleeps == [windows_attempt_delay(0), windows_attempt_delay(1)]

    def test_replace_gives_up_on_windows(self, fs, monkeypatch):
        """The last PermissionError should be raised and the tmp file cleaned up."""
        monkeypatch.setattr(atomic, 'IS_WINDOWS', True)
        sleeps = record_sleeps(monkeypatch)
        error = PermissionError(13, 'Permission denied')
        tmp = to_tmp_file('/data/a.txt')
        file_write(tmp, 'data')
        calls = break_function(monkeypatch, os, 'replace', [error] * WINDOWS_MAX_ATTEMPT)
        with pytest.raises(PermissionError) as e:
            replace_tmp(tmp, '/data/a.txt')
        assert e.value is error
        assert len(calls) == WINDOWS_MAX_ATTEMPT
        assert sleeps.sleeps == [windows_attempt_delay(attempt) for attempt in range(WINDOWS_MAX_ATTEMPT)]
        assert not os.path.exists(tmp)
        assert not os.path.exists('/data/a.txt')

    def test_replace_windows_other_error(self, fs, monkeypatch):
        """An unexpected error should not be retried, the tmp file is still cleaned up."""
        monkeypatch.setattr(atomic, 'IS_WINDOWS', True)
        sleeps = record_sleeps(monkeypatch)
        error = OSError('Other error')
        tmp = to_tmp_file('/data/a.txt')
        file_write(tmp, 'data')
        calls = break_function(monkeypatch, os, 'replace', [error])
        with pytest.raises(OSError) as e:
            replace_tmp(tmp, '/data/a.txt')
        assert e.value is error
        assert len(calls) == 1
        assert sleeps.sleeps == []
        assert not os.path.exists(tmp)

    @pytest.mark.parametrize('error', [PermissionError(13, 'Permission denied'), OSError('Other error')])
    def test_replace_posix_errors(self, fs, monkeypatch, error):
        """On the other platforms the error is raised right away, the tmp file cleaned up."""
        monkeypatch.setattr(atomic, 'IS_WINDOWS', False)
        tmp = to_tmp_file('/data/a.txt')
        file_write(tmp, 'data')
        calls = break_function(monkeypatch, os, 'replace', [error])
        with pytest.raises(type(error)) as e:
            replace_tmp(tmp, '/data/a.txt')
        assert e.value is error
        assert len(calls) == 1
        assert not os.path.exists(tmp)

    @pytest.mark.parametrize('unlink_error', [
        FileNotFoundError(2, 'No such file or directory'),
        OSError('Other error'),
    ])
    def test_replace_cleanup_error(self, fs, monkeypatch, unlink_error):
        """A tmp file that can not be cleaned up should not hide the replace error."""
        monkeypatch.setattr(atomic, 'IS_WINDOWS', False)
        error = OSError('Replace failed')
        tmp = to_tmp_file('/data/a.txt')
        file_write(tmp, 'data')
        break_function(monkeypatch, os, 'replace', [error])
        break_function(monkeypatch, os, 'unlink', [unlink_error])
        with pytest.raises(OSError) as e:
            replace_tmp(tmp, '/data/a.txt')
        assert e.value is error
