GemsFarming:
  args:
    ChangeFlagship:
      value: ship
      option: [ ship, ship_equip ]
    CommonCV:
      value: any
      option: [ any, langley, bogue, ranger, hermes ]
    ChangeVanguard:
      value: ship
      option: [ disabled, ship, ship_equip ]
    CommonDD:
      value: any
      option: [ any, favourite, aulick_or_foote , cassin_or_downes, z20_or_z21 ]
    CommissionLimit: true

EquipmentCode:
  args:
    ExportToConfig: true
    Config:
      dt: textarea
      value: ""

# Cross-nav variant groups: parents defined in `main` nav
GemsCampaign:
  parent: Campaign
  args:
    Name:
      dt: secondary-select
      value: 2-4
    Mode:
      dt: static-hide
      value: normal

GemsStopCondition:
  parent: StopCondition
  override_i18n: true
  args:
    RunCount:
      value: 0
      range: 0~999
    MapAchievement:
      dt: static
      value: non_stop

GemsSubmarine:
  parent: Submarine
  args:
    Fleet:
      dt: static
      value: 2
    Mode:
      dt: static-hide
      value: hunt_and_boss

GemsEmotionRecord:
  parent: EmotionRecord
  args:
    Value:
      value: 150
      range: 0~200
    Recover:
      dt: static
      value: dormitory_floor_2
