Main:
  groups:
    # with editable ServerUpdate for testing
    Scheduler: SchedulerUedit
    Campaign:
    StopCondition:
    Fleet1: Fleet
    Fleet2: Fleet
    Submarine:
    Emotion:
    Emotion1: EmotionRecord
    Emotion2: EmotionRecord
    HpControl:
    EnemyPriority:
    Hard: CampaignHard
  displays:
    - info: Main
      groups: Scheduler
    - Campaign
    - StopCondition
    - info: Fleet
      groups: [ Fleet1, Fleet2 ]
    - [ Emotion, Emotion1, Emotion2 ]
    - Submarine
    - HpControl
    - EnemyPriority
    - Hard
