import { browser } from "$app/environment";
// Import constants generated by the script
// @ts-ignore
import { DEFAULT_LANG, SUPPORTED_LANGS } from "$src/i18ngen/constants";
import { isElectron } from "$lib/use/useElectronEnv.svelte";
import { matchLanguage } from "./negotiate";

export type Lang = (typeof SUPPORTED_LANGS)[number];
// Host-level config value: a concrete language or 'system' (follow the
// system language). Only meaningful in an embedded session where the
// webapp host is the source of truth.
export type ConfigLang = Lang | "system";

// === DIRECT EXPORT OF RUNE ===
// This variable is imported by the generated static files.
// Svelte 5 tracks dependencies automatically when this is read.
let currentLang = $state<Lang>(DEFAULT_LANG);

// === Initialization ===
if (browser) {
  const match = document.cookie.match(new RegExp('(^| )alasio_lang=([^;]+)'));
  const saved = match ? match[2] : null;

  if (saved && (SUPPORTED_LANGS as readonly string[]).includes(saved)) {
    // Use saved preference
    currentLang = saved as Lang;
  } else {
    // Detect from browser
    const detected = matchLanguage(navigator.languages, SUPPORTED_LANGS, DEFAULT_LANG);
    currentLang = detected as Lang;
  }
}

/**
 * Apply a display language (always concrete) without reporting back to
 * the host. Used by the `alasio:lang` downlink: the host is the source of
 * truth, so host-driven changes must not loop back to it.
 */
function applyLang(lang: Lang) {
  if (lang === currentLang) return;
  currentLang = lang;
  if (browser) {
    document.cookie = `alasio_lang=${lang}; path=/; max-age=31536000`;
  }
}

/**
 * Report the user-chosen config value to the host (webapp main process).
 * The host is the source of truth: it derives the display language and
 * sends it back through the downlink. Remote browser sessions have no
 * parent container and never report.
 */
function reportLang(configLang: ConfigLang) {
  if (browser && isElectron.value) {
    window.parent.postMessage({ type: "alasio:lang", lang: configLang }, "*");
  }
}

// === Public API ===

/**
 * Switch language (user entry). Updates cookie and reloads page data.
 *
 * In an embedded session the value is reported to the host as the new
 * config value; 'system' keeps the current display language until the
 * host replies with the derived display value.
 */
export function setLang(l: ConfigLang) {
  if (l !== "system") applyLang(l);
  reportLang(l);
}

// Listen for the host-driven language downlink. The host sends the
// concrete display language whenever its config or system language
// changes; the cookie is updated so backend negotiation stays consistent.
if (browser) {
  window.addEventListener("message", (event: MessageEvent) => {
    if (event.source !== window.parent) return;
    const data = event.data;
    if (!data || typeof data !== "object") return;
    if (data.type === "alasio:lang" && typeof data.lang === "string") {
      if ((SUPPORTED_LANGS as readonly string[]).includes(data.lang)) {
        applyLang(data.lang as Lang);
      }
    }
  });
}

// Export state for read-only access if needed
export const i18nState = {
  get l() {
    return currentLang;
  },
};
