import { browser } from "$app/environment";
// Import constants generated by the script
// @ts-ignore
import { DEFAULT_LANG, SUPPORTED_LANGS } from "../../i18ngen/constants";
import { matchLanguage } from "./negotiate";

export type Lang = (typeof SUPPORTED_LANGS)[number];

// === DIRECT EXPORT OF RUNE ===
// This variable is imported by the generated static files.
// Svelte 5 tracks dependencies automatically when this is read.
let currentLang = $state<Lang>(DEFAULT_LANG);

// === Initialization ===
if (browser) {
  const saved = localStorage.getItem("lang");

  if (saved && (SUPPORTED_LANGS as readonly string[]).includes(saved)) {
    // Use saved preference
    currentLang = saved as Lang;
  } else {
    // Detect from browser
    const detected = matchLanguage(navigator.languages, SUPPORTED_LANGS, DEFAULT_LANG);
    currentLang = detected as Lang;
  }
}

// === Public API ===

/**
 * Switch language. Updates localStorage and reloads page data.
 */
export function setLang(l: Lang) {
  if (l === currentLang) return;
  currentLang = l;
  if (browser) {
    localStorage.setItem("lang", l);
  }
}

// Export state for read-only access if needed
export const i18nState = {
  get l() {
    return currentLang;
  },
};
