Scheduler:
  args:
    Enable:
      dt: enable
      value: false
    NextRun:
      dt: datetime
      value: 2020-01-01T00:00:00Z
    ServerUpdate:
      dt: static-hide
      value: "00:00"

# Scheduler is an alias of SchedulerU00
SchedulerU00:
  parent: Scheduler

SchedulerStatic:
  parent: Scheduler
  args:
    Enable:
      # TypeError: Literal may only contain None/integers/strings - typing.Literal[True] is not supported
      # msgspec does not allow Literal[True], so here's a string
      dt: static
      value: "enabled"

# SchedulerStatic is an alias of SchedulerStaticU00
SchedulerStaticU00:
  parent: SchedulerStatic

SchedulerUedit:
  parent: Scheduler
  args:
    ServerUpdate: "00:00"

SchedulerStaticUedit:
  parent: [ SchedulerStatic, SchedulerUedit ]

SchedulerU04:
  parent: Scheduler
  args:
    ServerUpdate:
      dt: static-hide
      value: "04:00"

SchedulerStaticU04:
  parent: [ SchedulerStatic, SchedulerU04 ]

# SchedulerEnable is a default-enabled Scheduler
SchedulerEnable:
  parent: Scheduler
  args:
    Enable:
      dt: enable
      value: true

# SchedulerEnable is an alias of SchedulerEnableU00
SchedulerEnableU00:
  parent: SchedulerEnable

SchedulerEnableUedit:
  parent: SchedulerEnable
  args:
    ServerUpdate: "00:00"

SchedulerEnableU04:
  parent: SchedulerEnable
  args:
    ServerUpdate:
      dt: static-hide
      value: "04:00"
