Scheduler:
  args:
    Enable: false
    NextRun: 2020-01-01T00:00:00Z
    ServerUpdate: "00:00"

SchedulerStatic:
  base: Scheduler
  args:
    Enable:
      # TypeError: Literal may only contain None/integers/strings - typing.Literal[True] is not supported
      # msgspec does not allow Literal[True], so here's a string
      dt: static
      value: "enabled"

SchedulerU00:
  base: Scheduler
  args:
    ServerUpdate:
      hide: true
      dt: static
      value: "00:00"

SchedulerStaticU00:
  base: Scheduler
  args:
    Enable:
      dt: static
      value: "enabled"
    ServerUpdate:
      hide: true
      dt: static
      value: "00:00"

SchedulerU04:
  base: Scheduler
  args:
    ServerUpdate:
      hide: true
      dt: static
      value: "04:00"

SchedulerStaticU04:
  base: Scheduler
  args:
    Enable:
      dt: static
      value: "enabled"
    ServerUpdate:
      hide: true
      dt: static
      value: "04:00"

#设备设置
#Alas设置
#
#主线图
#活动
#紧急委托
#退役设置
#
#收获，委托技能科研后宅
#每日任务，每日困难演习
#商店，商店商店船坞
#白嫖，白嫖抽卡小游戏
#
#大世界每日
#大世界高难
