Scheduler:
  args:
    Enable:
      dt: enable
      layout: desc
      fold_help: true
      value: false
    NextRun:
      dt: datetime
      layout: desc
      fold_help: true
      value: 2020-01-01T00:00:00Z
    ServerUpdate:
      hide: true
      dt: static
      value: "00:00"

# Scheduler is an alias of SchedulerU00
SchedulerU00:
  parent: Scheduler

SchedulerStatic:
  parent: Scheduler
  args:
    Enable:
      # TypeError: Literal may only contain None/integers/strings - typing.Literal[True] is not supported
      # msgspec does not allow Literal[True], so here's a string
      dt: static
      layout: desc
      fold_help: true
      value: "enabled"

# SchedulerStatic is an alias of SchedulerStaticU00
SchedulerStaticU00:
  parent: SchedulerStatic

SchedulerUedit:
  parent: Scheduler
  args:
    ServerUpdate: "00:00"

SchedulerStaticUedit:
  parent: [ SchedulerStatic, SchedulerUedit ]

SchedulerU04:
  parent: Scheduler
  args:
    ServerUpdate:
      hide: true
      dt: static
      value: "04:00"

SchedulerStaticU04:
  parent: [ SchedulerStatic, SchedulerU04 ]

#设备设置
#Alas设置
#
#主线图
#活动
#紧急委托
#退役设置
#
#收获，委托技能科研后宅
#每日任务，每日困难演习
#商店，商店商店船坞
#白嫖，白嫖抽卡小游戏
#
#大世界每日
#大世界高难
